set_property SRC_FILE_INFO {cfile:C:/Users/Stan/Documents/Git/System-Numeric-Exercices/Exercise2/Exercise2.srcs/constrs_1/new/Constaints.xdc rfile:../../../Exercise2.srcs/constrs_1/new/Constaints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA20  [get_ports Aff_enable]; set_property IOSTANDARD LVCMOS33 [get_ports Aff_enable]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V22   [get_ports Ya];  set_property IOSTANDARD LVCMOS33 [get_ports Ya]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W22   [get_ports Yb];  set_property IOSTANDARD LVCMOS33 [get_ports Yb]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W21   [get_ports Yc];  set_property IOSTANDARD LVCMOS33 [get_ports Yc]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y22   [get_ports Yd];  set_property IOSTANDARD LVCMOS33 [get_ports Yd]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y21   [get_ports Ye];  set_property IOSTANDARD LVCMOS33 [get_ports Ye]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB22  [get_ports Yf];  set_property IOSTANDARD LVCMOS33 [get_ports Yf]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA21  [get_ports Yg];  set_property IOSTANDARD LVCMOS33 [get_ports Yg]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U21   [get_ports A];   set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V20   [get_ports B];   set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W20   [get_ports C];   set_property IOSTANDARD LVCMOS33 [get_ports C]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U20   [get_ports D];   set_property IOSTANDARD LVCMOS33 [get_ports D]
