set_property PACKAGE_PIN K19   [get_ports clk];     set_property IOSTANDARD LVCMOS33 [get_ports clk];  set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk}]
set_property PACKAGE_PIN G13   [get_ports led[0]];  set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property PACKAGE_PIN H14   [get_ports led[1]];  set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property PACKAGE_PIN G15   [get_ports led[2]];  set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property PACKAGE_PIN G16   [get_ports led[3]];  set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property PACKAGE_PIN H17   [get_ports led[4]];  set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property PACKAGE_PIN T18   [get_ports reset_n]; set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
set_property PACKAGE_PIN U21   [get_ports enable];  set_property IOSTANDARD LVCMOS33 [get_ports enable]
