set_property SRC_FILE_INFO {cfile:C:/Users/Stan/Documents/Git/System-Numeric-Exercices/Project_CP/Project_CP.srcs/constrs_1/new/Constraints.xdc rfile:../../../Project_CP.srcs/constrs_1/new/Constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20   [get_ports A[0]]; set_property IOSTANDARD LVCMOS33 [get_ports A[0]]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H22   [get_ports A[1]]; set_property IOSTANDARD LVCMOS33 [get_ports A[1]]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J21   [get_ports B[0]]; set_property IOSTANDARD LVCMOS33 [get_ports B[0]]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J22   [get_ports B[1]]; set_property IOSTANDARD LVCMOS33 [get_ports B[1]]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K21   [get_ports C[0]]; set_property IOSTANDARD LVCMOS33 [get_ports C[0]]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K22   [get_ports C[1]]; set_property IOSTANDARD LVCMOS33 [get_ports C[1]]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G13   [get_ports S[0]]; set_property IOSTANDARD LVCMOS33 [get_ports S[0]]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14   [get_ports S[1]]; set_property IOSTANDARD LVCMOS33 [get_ports S[1]]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15   [get_ports S[2]]; set_property IOSTANDARD LVCMOS33 [get_ports S[2]]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U21   [get_ports sel];  set_property IOSTANDARD LVCMOS33 [get_ports sel]
