set_property PACKAGE_PIN K19   [get_ports clk];        set_property IOSTANDARD LVCMOS33 [get_ports clk];  set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk}]
set_property PACKAGE_PIN T18   [get_ports reset_n];    set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
set_property PACKAGE_PIN N22   [get_ports divider[0]]; set_property IOSTANDARD LVCMOS33 [get_ports divider[0]]
set_property PACKAGE_PIN G17   [get_ports divider[1]]; set_property IOSTANDARD LVCMOS33 [get_ports divider[1]]
set_property PACKAGE_PIN G18   [get_ports divider[2]]; set_property IOSTANDARD LVCMOS33 [get_ports divider[2]]
set_property PACKAGE_PIN H18   [get_ports divider[3]]; set_property IOSTANDARD LVCMOS33 [get_ports divider[3]]
set_property PACKAGE_PIN H20   [get_ports divider[4]]; set_property IOSTANDARD LVCMOS33 [get_ports divider[4]]
set_property PACKAGE_PIN J17   [get_ports divider[5]]; set_property IOSTANDARD LVCMOS33 [get_ports divider[5]]
set_property PACKAGE_PIN J20   [get_ports divider[6]]; set_property IOSTANDARD LVCMOS33 [get_ports divider[6]]
set_property PACKAGE_PIN H15   [get_ports divider[7]]; set_property IOSTANDARD LVCMOS33 [get_ports divider[7]]
set_property PACKAGE_PIN A18   [get_ports div];        set_property IOSTANDARD LVCMOS33 [get_ports div]
