set_property SRC_FILE_INFO {cfile:C:/Users/Stan/Documents/Git/System-Numeric-Exercices/Exercice4/Exercice4.srcs/constrs_1/new/constraints.xdc rfile:../../../Exercice4.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U21   [get_ports sel];     set_property IOSTANDARD LVCMOS33 [get_ports sel]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V20   [get_ports input1];  set_property IOSTANDARD LVCMOS33 [get_ports input1]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W20   [get_ports input2];  set_property IOSTANDARD LVCMOS33 [get_ports input2]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U20   [get_ports input3];  set_property IOSTANDARD LVCMOS33 [get_ports input3]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18   [get_ports sel_out]; set_property IOSTANDARD LVCMOS33 [get_ports sel_out]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A19   [get_ports out1];    set_property IOSTANDARD LVCMOS33 [get_ports out1]
