set_property SRC_FILE_INFO {cfile:C:/Users/Stan/Documents/Git/System-Numeric-Exercices/Exercice_20/Exercice_20.srcs/constrs_1/new/Constraints.xdc rfile:../../../Exercice_20.srcs/constrs_1/new/Constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K19   [get_ports clk];     set_property IOSTANDARD LVCMOS33 [get_ports clk];  set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G13   [get_ports led[0]];  set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14   [get_ports led[1]];  set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15   [get_ports led[2]];  set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16   [get_ports led[3]];  set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17   [get_ports led[4]];  set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T18   [get_ports reset_n]; set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U21   [get_ports enable];  set_property IOSTANDARD LVCMOS33 [get_ports enable]
