set_property SRC_FILE_INFO {cfile:C:/Users/Stan/Documents/Git/System-Numeric-Exercices/Exercice_23/Exercice_23.srcs/constrs_1/new/Constraints.xdc rfile:../../../Exercice_23.srcs/constrs_1/new/Constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J19   [get_ports clk];       set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T18   [get_ports reset_n];   set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U21   [get_ports capteur];   set_property IOSTANDARD LVCMOS33 [get_ports capteur]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U20   [get_ports test];      set_property IOSTANDARD LVCMOS33 [get_ports test]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18   [get_ports feuxP1[0]]; set_property IOSTANDARD LVCMOS33 [get_ports feuxP1[0]]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B20   [get_ports feuxP2[0]]; set_property IOSTANDARD LVCMOS33 [get_ports feuxP2[0]]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20   [get_ports feuxS[0]];  set_property IOSTANDARD LVCMOS33 [get_ports feuxS[0]]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B16   [get_ports feuxP1[1]]; set_property IOSTANDARD LVCMOS33 [get_ports feuxP1[1]]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B18   [get_ports feuxP2[1]]; set_property IOSTANDARD LVCMOS33 [get_ports feuxP2[1]]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A19   [get_ports feuxS[1]];  set_property IOSTANDARD LVCMOS33 [get_ports feuxS[1]]
