set_property PACKAGE_PIN U21   [get_ports A];   set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property PACKAGE_PIN V20   [get_ports B];   set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property PACKAGE_PIN W20   [get_ports C];   set_property IOSTANDARD LVCMOS33 [get_ports C]
set_property PACKAGE_PIN A18   [get_ports S];   set_property IOSTANDARD LVCMOS33 [get_ports S]
set_property PACKAGE_PIN B18   [get_ports Y];   set_property IOSTANDARD LVCMOS33 [get_ports Y]