set_property SRC_FILE_INFO {cfile:C:/Users/Stan/Documents/Git/System-Numeric-Exercices/Exercice10/Exercice10.srcs/constrs_1/new/Constraint.xdc rfile:../../../Exercice10.srcs/constrs_1/new/Constraint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20   [get_ports ADR[0]];    set_property IOSTANDARD LVCMOS33 [get_ports ADR[0]]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H22   [get_ports ADR[1]];    set_property IOSTANDARD LVCMOS33 [get_ports ADR[1]]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J21   [get_ports ADR[2]];    set_property IOSTANDARD LVCMOS33 [get_ports ADR[2]]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J22   [get_ports ADR[3]];    set_property IOSTANDARD LVCMOS33 [get_ports ADR[3]]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K21   [get_ports ADR[4]];    set_property IOSTANDARD LVCMOS33 [get_ports ADR[4]]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K22   [get_ports ADR[5]];    set_property IOSTANDARD LVCMOS33 [get_ports ADR[5]]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M21   [get_ports ADR[6]];    set_property IOSTANDARD LVCMOS33 [get_ports ADR[6]]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22   [get_ports ADR[7]];    set_property IOSTANDARD LVCMOS33 [get_ports ADR[7]]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N22   [get_ports ADR[8]];    set_property IOSTANDARD LVCMOS33 [get_ports ADR[8]]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17   [get_ports ADR[9]];    set_property IOSTANDARD LVCMOS33 [get_ports ADR[9]]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G18   [get_ports ADR[10]];   set_property IOSTANDARD LVCMOS33 [get_ports ADR[10]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18   [get_ports ADR[11]];   set_property IOSTANDARD LVCMOS33 [get_ports ADR[11]]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H20   [get_ports ADR[12]];   set_property IOSTANDARD LVCMOS33 [get_ports ADR[12]]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J17   [get_ports ADR[13]];   set_property IOSTANDARD LVCMOS33 [get_ports ADR[13]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20   [get_ports ADR[14]];   set_property IOSTANDARD LVCMOS33 [get_ports ADR[14]]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15   [get_ports ADR[15]];   set_property IOSTANDARD LVCMOS33 [get_ports ADR[15]]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B16   [get_ports CS_RAM];    set_property IOSTANDARD LVCMOS33 [get_ports CS_RAM]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B18   [get_ports CS_FLASH];  set_property IOSTANDARD LVCMOS33 [get_ports CS_FLASH]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A19   [get_ports CS_EEPROM]; set_property IOSTANDARD LVCMOS33 [get_ports CS_EEPROM]
