set_property SRC_FILE_INFO {cfile:C:/Users/Stan/Documents/Git/System-Numeric-Exercices/Exercice16/Exercice16.srcs/constrs_1/new/Constraints.xdc rfile:../../../Exercice16.srcs/constrs_1/new/Constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K19   [get_ports clk];      set_property IOSTANDARD LVCMOS33 [get_ports clk];  set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G13   [get_ports dout[0]];  set_property IOSTANDARD LVCMOS33 [get_ports dout[0]]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14   [get_ports dout[1]];  set_property IOSTANDARD LVCMOS33 [get_ports dout[1]]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15   [get_ports dout[2]];  set_property IOSTANDARD LVCMOS33 [get_ports dout[2]]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16   [get_ports dout[3]];  set_property IOSTANDARD LVCMOS33 [get_ports dout[3]]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17   [get_ports dout[4]];  set_property IOSTANDARD LVCMOS33 [get_ports dout[4]]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16   [get_ports dout[5]];  set_property IOSTANDARD LVCMOS33 [get_ports dout[5]]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17   [get_ports dout[6]];  set_property IOSTANDARD LVCMOS33 [get_ports dout[6]]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L20   [get_ports dout[7]];  set_property IOSTANDARD LVCMOS33 [get_ports dout[7]]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L21   [get_ports dout[8]];  set_property IOSTANDARD LVCMOS33 [get_ports dout[8]]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L19   [get_ports dout[9]];  set_property IOSTANDARD LVCMOS33 [get_ports dout[9]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L18   [get_ports dout[10]]; set_property IOSTANDARD LVCMOS33 [get_ports dout[10]]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16   [get_ports dout[11]]; set_property IOSTANDARD LVCMOS33 [get_ports dout[11]]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15   [get_ports dout[12]]; set_property IOSTANDARD LVCMOS33 [get_ports dout[12]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M20   [get_ports dout[13]]; set_property IOSTANDARD LVCMOS33 [get_ports dout[13]]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N19   [get_ports dout[14]]; set_property IOSTANDARD LVCMOS33 [get_ports dout[14]]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N20   [get_ports dout[15]]; set_property IOSTANDARD LVCMOS33 [get_ports dout[15]]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T18   [get_ports reset_n];  set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U21   [get_ports serin];    set_property IOSTANDARD LVCMOS33 [get_ports serin]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U20   [get_ports enable];   set_property IOSTANDARD LVCMOS33 [get_ports enable]
