set_property SRC_FILE_INFO {cfile:C:/Users/Stan/Documents/Git/System-Numeric-Exercices/Exercice1/Exercice1.srcs/constrs_1/new/IO_Const.xdc rfile:../../../Exercice1.srcs/constrs_1/new/IO_Const.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U21   [get_ports A];   set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V20   [get_ports B];   set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W20   [get_ports C];   set_property IOSTANDARD LVCMOS33 [get_ports C]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18   [get_ports S];   set_property IOSTANDARD LVCMOS33 [get_ports S]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B18   [get_ports Y];   set_property IOSTANDARD LVCMOS33 [get_ports Y]
