set_property SRC_FILE_INFO {cfile:C:/Users/Stan/Documents/Git/System-Numeric-Exercices/Exercice3/Exercice3.srcs/constrs_1/new/constraints.xdc rfile:../../../Exercice3.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U21   [get_ports BCD[0]]; set_property IOSTANDARD LVCMOS33 [get_ports BCD[0]]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V20   [get_ports BCD[1]]; set_property IOSTANDARD LVCMOS33 [get_ports BCD[1]]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W20   [get_ports BCD[2]]; set_property IOSTANDARD LVCMOS33 [get_ports BCD[2]]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U20   [get_ports BCD[3]]; set_property IOSTANDARD LVCMOS33 [get_ports BCD[3]]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA20  [get_ports Aff_enable]; set_property IOSTANDARD LVCMOS33 [get_ports Aff_enable]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V22   [get_ports Ya];         set_property IOSTANDARD LVCMOS33 [get_ports Ya]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W22   [get_ports Yb];         set_property IOSTANDARD LVCMOS33 [get_ports Yb]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W21   [get_ports Yc];         set_property IOSTANDARD LVCMOS33 [get_ports Yc]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y22   [get_ports Yd];         set_property IOSTANDARD LVCMOS33 [get_ports Yd]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y21   [get_ports Ye];         set_property IOSTANDARD LVCMOS33 [get_ports Ye]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB22  [get_ports Yf];         set_property IOSTANDARD LVCMOS33 [get_ports Yf]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA21  [get_ports Yg];         set_property IOSTANDARD LVCMOS33 [get_ports Yg]
