set_property SRC_FILE_INFO {cfile:C:/Users/Stan/Documents/Git/System-Numeric-Exercices/Exercice9/Exercice9.srcs/constrs_1/new/Constraints.xdc rfile:../../../Exercice9.srcs/constrs_1/new/Constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20   [get_ports ina[0]]; set_property IOSTANDARD LVCMOS33 [get_ports ina[0]]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H22   [get_ports ina[1]]; set_property IOSTANDARD LVCMOS33 [get_ports ina[1]]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J21   [get_ports ina[2]]; set_property IOSTANDARD LVCMOS33 [get_ports ina[2]]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J22   [get_ports ina[3]]; set_property IOSTANDARD LVCMOS33 [get_ports ina[3]]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K21   [get_ports ina[4]]; set_property IOSTANDARD LVCMOS33 [get_ports ina[4]]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K22   [get_ports ina[5]]; set_property IOSTANDARD LVCMOS33 [get_ports ina[5]]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M21   [get_ports ina[6]]; set_property IOSTANDARD LVCMOS33 [get_ports ina[6]]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22   [get_ports ina[7]]; set_property IOSTANDARD LVCMOS33 [get_ports ina[7]]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N22   [get_ports inb[0]]; set_property IOSTANDARD LVCMOS33 [get_ports inb[0]]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17   [get_ports inb[1]]; set_property IOSTANDARD LVCMOS33 [get_ports inb[1]]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G18   [get_ports inb[2]]; set_property IOSTANDARD LVCMOS33 [get_ports inb[2]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18   [get_ports inb[3]]; set_property IOSTANDARD LVCMOS33 [get_ports inb[3]]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H20   [get_ports inb[4]]; set_property IOSTANDARD LVCMOS33 [get_ports inb[4]]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J17   [get_ports inb[5]]; set_property IOSTANDARD LVCMOS33 [get_ports inb[5]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20   [get_ports inb[6]]; set_property IOSTANDARD LVCMOS33 [get_ports inb[6]]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15   [get_ports inb[7]]; set_property IOSTANDARD LVCMOS33 [get_ports inb[7]]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U21   [get_ports ebl];    set_property IOSTANDARD LVCMOS33 [get_ports ebl]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B16   [get_ports EG];     set_property IOSTANDARD LVCMOS33 [get_ports EG]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B18   [get_ports PG];     set_property IOSTANDARD LVCMOS33 [get_ports PG]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A19   [get_ports PP];     set_property IOSTANDARD LVCMOS33 [get_ports PP]
