set_property PACKAGE_PIN U21   [get_ports sel];     set_property IOSTANDARD LVCMOS33 [get_ports sel]
set_property PACKAGE_PIN V20   [get_ports input1];  set_property IOSTANDARD LVCMOS33 [get_ports input1]
set_property PACKAGE_PIN W20   [get_ports input2];  set_property IOSTANDARD LVCMOS33 [get_ports input2]
set_property PACKAGE_PIN U20   [get_ports input3];  set_property IOSTANDARD LVCMOS33 [get_ports input3]
set_property PACKAGE_PIN A18   [get_ports sel_out]; set_property IOSTANDARD LVCMOS33 [get_ports sel_out]
set_property PACKAGE_PIN A19   [get_ports out1];    set_property IOSTANDARD LVCMOS33 [get_ports out1]