set_property SRC_FILE_INFO {cfile:C:/Users/Stan/Documents/Git/System-Numeric-Exercices/Exercice3/Exercice3.srcs/constrs_1/new/Constraints.xdc rfile:../../../Exercice3.srcs/constrs_1/new/Constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA20  [get_ports Aff_enable]; set_property IOSTANDARD LVCMOS33 [get_ports Aff_enable]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V22   [get_ports Aff[0]];     set_property IOSTANDARD LVCMOS33 [get_ports Aff[0]]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W22   [get_ports Aff[1]];     set_property IOSTANDARD LVCMOS33 [get_ports Aff[1]]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W21   [get_ports Aff[2]];     set_property IOSTANDARD LVCMOS33 [get_ports Aff[2]]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y22   [get_ports Aff[3]];     set_property IOSTANDARD LVCMOS33 [get_ports Aff[3]]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y21   [get_ports Aff[4]];     set_property IOSTANDARD LVCMOS33 [get_ports Aff[4]]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB22  [get_ports Aff[5]];     set_property IOSTANDARD LVCMOS33 [get_ports Aff[5]]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA21  [get_ports Aff[6]];     set_property IOSTANDARD LVCMOS33 [get_ports Aff[6]]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U21   [get_ports BCD[0]];     set_property IOSTANDARD LVCMOS33 [get_ports BCD[0]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V20   [get_ports BCD[1]];     set_property IOSTANDARD LVCMOS33 [get_ports BCD[1]]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W20   [get_ports BCD[2]];     set_property IOSTANDARD LVCMOS33 [get_ports BCD[2]]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U20   [get_ports BCD[3]];     set_property IOSTANDARD LVCMOS33 [get_ports BCD[3]]
