set_property SRC_FILE_INFO {cfile:C:/Users/Stan/Documents/Git/System-Numeric-Exercices/Exercice14/Exercice14.srcs/constrs_1/new/Constraints.xdc rfile:../../../Exercice14.srcs/constrs_1/new/Constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20   [get_ports d[0]];    set_property IOSTANDARD LVCMOS33 [get_ports d[0]]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H22   [get_ports d[1]];    set_property IOSTANDARD LVCMOS33 [get_ports d[1]]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J21   [get_ports d[2]];    set_property IOSTANDARD LVCMOS33 [get_ports d[2]]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J22   [get_ports d[3]];    set_property IOSTANDARD LVCMOS33 [get_ports d[3]]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K21   [get_ports d[4]];    set_property IOSTANDARD LVCMOS33 [get_ports d[4]]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K22   [get_ports d[5]];    set_property IOSTANDARD LVCMOS33 [get_ports d[5]]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M21   [get_ports d[6]];    set_property IOSTANDARD LVCMOS33 [get_ports d[6]]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22   [get_ports d[7]];    set_property IOSTANDARD LVCMOS33 [get_ports d[7]]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G13   [get_ports q[0]];    set_property IOSTANDARD LVCMOS33 [get_ports q[0]]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14   [get_ports q[1]];    set_property IOSTANDARD LVCMOS33 [get_ports q[1]]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15   [get_ports q[2]];    set_property IOSTANDARD LVCMOS33 [get_ports q[2]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16   [get_ports q[3]];    set_property IOSTANDARD LVCMOS33 [get_ports q[3]]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17   [get_ports q[4]];    set_property IOSTANDARD LVCMOS33 [get_ports q[4]]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16   [get_ports q[5]];    set_property IOSTANDARD LVCMOS33 [get_ports q[5]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17   [get_ports q[6]];    set_property IOSTANDARD LVCMOS33 [get_ports q[6]]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L20   [get_ports q[7]];    set_property IOSTANDARD LVCMOS33 [get_ports q[7]]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U21   [get_ports reset_n]; set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V20   [get_ports reset_s]; set_property IOSTANDARD LVCMOS33 [get_ports reset_s]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W20   [get_ports enable];  set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K19   [get_ports clk]; set_property IOSTANDARD LVCMOS33 [get_ports clk];  set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk}]
