set_property PACKAGE_PIN K19   [get_ports clk];     set_property IOSTANDARD LVCMOS33 [get_ports clk];  set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk}]
set_property PACKAGE_PIN T18   [get_ports reset_n]; set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
set_property PACKAGE_PIN U21   [get_ports d];       set_property IOSTANDARD LVCMOS33 [get_ports d]
set_property PACKAGE_PIN U20   [get_ports enable];  set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property PACKAGE_PIN B16   [get_ports q];       set_property IOSTANDARD LVCMOS33 [get_ports q]